"""empty message

Revision ID: ca2b47b6fb12
Revises: 
Create Date: 2019-10-04 22:00:29.186144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca2b47b6fb12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('image_url', sa.String(length=300), nullable=False),
    sa.Column('Created_by', sa.String(length=50), nullable=False),
    sa.Column('Category', sa.String(length=50), nullable=False),
    sa.Column('tags', sa.String(length=300), nullable=True),
    sa.Column('Content', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=85), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('Article')
    # ### end Alembic commands ###
